In [26]:
import numpy as np

np.array([1,2,3,4])
np.arange(0, 10, 2)
np.zeros((2, 3), dtype='i4')
np.ones((2, 3), dtype='i1')
np.linspace(0, 10, 20)
np.logspace(0, 2, 5)


ary = np.arange(1,10).reshape(3,3)
ary

ary1 = ary.flatten()
ary1[0] = 100
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
import numpy as np

arr = np.random.randint(0, 9, size=(3,3,3))

print(arr[:2, :2, :2])  # 获取三维数组前两页，每页的前两行，每行的前两列

[[[6 0]
  [3 1]]

 [[3 1]
  [2 0]]]


In [44]:
import numpy as np
a = np.arange(0, 10)
mask = [True, False,True, False,True, False,True, False,True, False]
print(a[mask])
print(a[[2,4,6,8]])

[0 2 4 6 8]
[2 4 6 8]


In [42]:
import numpy as np

arr1 = np.arange(1, 7).reshape(2,3)
arr2 = np.arange(11, 17).reshape(3,2)
arr = arr1.dot(arr2)
print(arr)
np.dot(arr1, arr2)

[[ 82  88]
 [199 214]]


array([[ 82,  88],
       [199, 214]])

In [48]:

import numpy as np

arr1 = np.arange(1, 7).reshape(2,3)
print(arr1)
print(arr1.T)
print(arr1.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [49]:
import numpy as np

arr = np.arange(32).reshape(8,4)
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [51]:
print(arr[np.ix_([0,3,5],[0,3,2])])

[[ 0  3  2]
 [12 15 14]
 [20 23 22]]
