In [5]:
# 构造ndarray数组
import numpy as np

ary = np.array([1, 2, 3, 4, 5, 6])
print(ary, type(ary))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


array([3, 4, 5, 6, 7, 8])

In [15]:
# 数组与数的运算

import numpy as np

ary = np.array([1, 2, 3, 4, 5, 6])
# 原始数据
print("原始数据    ", ary)
# 加法
print("原始数据 + 2", ary + 2)
# 减法
print("原始数据 - 2", ary - 2)
# 乘法
print("原始数据 * 2", ary * 2)
# 除法
print("原始数据 / 2", ary / 2)
# 幂运算
print("原始数据 ** 2", ary ** 2)
# 取模
print("原始数据 % 2", ary % 2)
# 比较
print("原始数据 > 3", ary > 3)
print("原始数据 < 3", ary < 3)
print("原始数据 == 3", ary == 3)
print("原始数据 != 3", ary != 3)

# 数组与数组进行运算
ary1 = ary
ary2 = np.array([7, 8, 9, 10, 11, 12])

print("ary1 + ary2", ary1 + ary2)
print("ary1 - ary2", ary1 - ary2)
print("ary1 * ary2", ary1 * ary2)
print("ary1 / ary2", ary1 / ary2)
print("ary1 % ary2", ary1 % ary2)
print("ary1 ** ary2", ary1 ** ary2)
print("ary1 > ary2", ary1 > ary2)
print("ary1 < ary2", ary1 < ary2)

原始数据     [1 2 3 4 5 6]
原始数据 + 2 [3 4 5 6 7 8]
原始数据 - 2 [-1  0  1  2  3  4]
原始数据 * 2 [ 2  4  6  8 10 12]
原始数据 / 2 [0.5 1.  1.5 2.  2.5 3. ]
原始数据 ** 2 [ 1  4  9 16 25 36]
原始数据 % 2 [1 0 1 0 1 0]
原始数据 > 3 [False False False  True  True  True]
原始数据 < 3 [ True  True False False False False]
原始数据 == 3 [False False  True False False False]
原始数据 != 3 [ True  True False  True  True  True]
ary1 + ary2 [ 8 10 12 14 16 18]
ary1 - ary2 [-6 -6 -6 -6 -6 -6]
ary1 * ary2 [ 7 16 27 40 55 72]
ary1 / ary2 [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]
ary1 % ary2 [1 2 3 4 5 6]
ary1 ** ary2 [          1         256       19683     1048576    48828125 -2118184960]
ary1 > ary2 [False False False False False False]
ary1 < ary2 [ True  True  True  True  True  True]


In [17]:
import numpy as np
ary = np.arange(0, 10, 2)
print(ary)


[0 2 4 6 8]


In [36]:
import numpy as np
np.zeros(10, dtype=np.int8)

np.zeros(10, dtype=np.float16)

np.ones(10, dtype=np.int8)
np.ones(10, dtype=np.float16)

np.zeros_like([1,2,3,4])
np.ones_like([1,2,3,4])

array([1, 1, 1, 1])

In [38]:
import numpy as np

ary = np.arange(1, 11)
# ary = ary.reshape((5, 2))
print(ary, ary.shape)
print(ary.ndim)
ary = np.array([
  [1,2,3],
  [4,5,6]
])
print(ary, ary.shape)

print(ary.ndim)

[ 1  2  3  4  5  6  7  8  9 10] (10,)
1
[[1 2 3]
 [4 5 6]] (2, 3)
2


In [39]:
import numpy as np
ary = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# 观察维度，size，len的区别
print(ary.shape, ary.size, len(ary))

(2, 4) 8 2


In [40]:
import numpy as np
ary = np.array([1, 2, 3, 4, 5, 6])
print(type(ary), ary, ary.dtype)
# 转换ary元素的类型
b = ary.astype(float)
print(type(b), b, b.dtype)
#转换ary元素的类型
c = ary.astype(str)
print(type(c), c, c.dtype)

<class 'numpy.ndarray'> [1 2 3 4 5 6] int32
<class 'numpy.ndarray'> [1. 2. 3. 4. 5. 6.] float64
<class 'numpy.ndarray'> ['1' '2' '3' '4' '5' '6'] <U11


In [43]:
import numpy as np
a = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
print(a, a.shape)
print(a[0])
print(a[0][0])
print(a[0, 0])
print(a[0][0][0])
print(a[0,0,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
[[1 2]
 [3 4]]
[1 2]
[1 2]
1
1


In [59]:
import numpy as np

data=[
	('zs', [90, 80, 85], 15),
	('ls', [92, 81, 83], 16),
	('ww', [95, 85, 95], 15)
]

# a = np.array(data, dtype='U3, 3int32, int32')

# b = np.array(data, dtype=[('name', 'str_', 3),
#                     ('scores', 'int32', 3),
#                     ('ages', 'int32', 1)])

# c = np.array(data, dtype={'names': ['name', 'scores', 'ages'],
#                     'formats': ['U3', '3int32', 'int32']})

# d = np.array(data, dtype={'name': ('U3', 0),
#                     'scores': ('3i4', 16),
#                     'age': ('i4', 28)})


# e = np.array([0x1234, 0x5667],
#              dtype=('u2', {'lowc': ('u1', 0),
#                            'hignc': ('u1', 1)}))
# print('%x' % e[0])
# print('%x %x' % (e['lowc'][0], e['hignc'][0]))

f = np.array(['2011', '2012-01-01', '2013-01-01 01:01:01',
              '2011-02-01'])
f = f.astype('M8[D]')
f = f.astype('int32')
print(f[3]-f[0])


31


In [63]:
import numpy as np
a = np.arange(1, 9)
print(a)		# [1 2 3 4 5 6 7 8]

b = a.reshape(2, 4)	#视图变维  : 变为2行4列的二维数组
print(b)
b[0, 0]=10
print("修改b", b)
print("修改b后的a", a)

c = b.reshape(2, 2, 2) #视图变维    变为2页2行2列的三维数组
print(c)

d = c.ravel()	#视图变维	变为1维数组
print(d)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
修改b [[10  2  3  4]
 [ 5  6  7  8]]
修改b后的a [10  2  3  4  5  6  7  8]
[[[10  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]]
[10  2  3  4  5  6  7  8]


In [64]:
import numpy as np
a = np.arange(1, 9)
print(a)		# [1 2 3 4 5 6 7 8]

b = a.reshape(2, 4)	#视图变维  : 变为2行4列的二维数组
print(b)
b[0, 0]=10
print("修改b", b)
print("修改b后的a", a)

c = b.reshape(2, 2, 2) #视图变维    变为2页2行2列的三维数组
print(c)

d = c.ravel()	#视图变维	变为1维数组
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
修改b [[10  2  3  4]
 [ 5  6  7  8]]
修改b后的a [10  2  3  4  5  6  7  8]
[[[10  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]]
[10  2  3  4  5  6  7  8]


In [70]:
import numpy as np
a = np.arange(1, 9)		# [1 2 3 4 5 6 7 8]

b = a.reshape(2, 4)	#视图变维  : 变为2行4列的二维数组

e = b.flatten()  # 复制变维
print("e", e)
a += 10   # a中的每个元素加10
print("a", a,"\n","b", b, "\n","e", e)  # a发生变化，b同时发生变化，e不发生变化

e [1 2 3 4 5 6 7 8]
a [11 12 13 14 15 16 17 18] 
 b [[11 12 13 14]
 [15 16 17 18]] 
 e [1 2 3 4 5 6 7 8]


In [83]:
import numpy as np
a = np.arange(1, 10)
print("{:15}".format("a:"), a) # 1,2,...,9
print("{:15}".format('a[:3]:'), a[:3]) # 1,2,3
print("{:15}".format('a[3:6]:'), a[3:6]) # 4,5,6
print("{:15}".format('a[6:]:'), a[6:]) # 7, 8, 9
print("{:15}".format('a[::-1]:'), a[::-1]) # 反序
print("{:15}".format('a[:-4:-1]:'), a[:-4:-1]) # 9, 8, 7
print("{:15}".format('a[-4:-7:-1]:'), a[-4:-7:-1]) # 6, 5, 4
print("{:15}".format('a[-7::-1]:'), a[-7::-1]) # 3 2 1
print("{:15}".format('a[::]:'), a[::]) # 1 2 3 4 5 6 7 8 9
print("{:15}".format('a[:]:'), a[:]) # 1 2 3 4 5 6 7 8 9

a:              [1 2 3 4 5 6 7 8 9]
a[:3]:          [1 2 3]
a[3:6]:         [4 5 6]
a[6:]:          [7 8 9]
a[::-1]:        [9 8 7 6 5 4 3 2 1]
a[:-4:-1]:      [9 8 7]
a[-4:-7:-1]:    [6 5 4]
a[-7::-1]:      [3 2 1]
a[::]:          [1 2 3 4 5 6 7 8 9]
a[:]:           [1 2 3 4 5 6 7 8 9]


In [86]:
import numpy as np
a = np.arange(1, 10)
a.resize((3,3))
print(a)

print(a[:2,:2])  # 获取3*3二维数组的前两行和前两列
print(a[::2,:])  # 获取3*3二维数组的一三两行
print(a[::2,::2])  # 获取3*3二维数组的一三两行和一三两列



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [7 9]]


In [90]:
import numpy as np

a = np.arange(1, 101)
mask = (a % 3 == 0) & (a % 7 == 0)
print(a[mask])

names = np.array(['Apple', 'MI', 'Vivo', 'Oppo', 'HuaWei'])

rank = [1,4,0,3,2]
print(names[rank])

[21 42 63 84]
['MI' 'HuaWei' 'Apple' 'Oppo' 'Vivo']


In [94]:
import numpy as np
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a, b))
print(c)
# 垂直方向完成拆分操作，生成两个数组
d, e = np.vsplit(c, 2)
print(d)
print(e)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
# 水平方向完成组合操作，生成新数组
c = np.hstack((a, b))
print(c)

# 水平方向完成拆分操作，生成两个数组
d, e = np.hsplit(c, 2)
print(d)
print(e)

In [97]:
import numpy as np
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a, '-->a')
print(b, '-->b')

# 深度方向（3维）完成组合操作，生成新数组
i = np.dstack((a, b))
print(i, '-->i')
# 深度方向（3维）完成拆分操作，生成两个数组
k, l = np.dsplit(i, 2)
print(k, '-->k')
print(l, '-->l')

[[1 2 3]
 [4 5 6]] -->a
[[ 7  8  9]
 [10 11 12]] -->b
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]] -->i
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]] -->k
[[[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] -->l


In [98]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4])
# 填充b数组使其长度与a相同,头部添加0个元素，尾部添加1个元素
b = np.pad(b, pad_width=(0, 1), mode='constant', constant_values=-1)
print(b)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a, b))
print(c)

[ 1  2  3  4 -1]
[[ 1  2  3  4  5]
 [ 1  2  3  4 -1]]


In [100]:
import numpy as np
a = np.arange(1,9)		#[1, 2, 3, 4, 5, 6, 7, 8]
b = np.arange(9,17)		#[9,10,11,12,13,14,15,16]
#把两个数组摞在一起成两行
c = np.row_stack((a, b))
print(c)
#把两个数组组合在一起成两列
d = np.column_stack((a, b))
print(d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  9]
 [ 2 10]
 [ 3 11]
 [ 4 12]
 [ 5 13]
 [ 6 14]
 [ 7 15]
 [ 8 16]]


In [101]:
import numpy as np
a = np.array([[1 + 1j, 2 + 4j, 3 + 7j],
              [4 + 2j, 5 + 5j, 6 + 8j],
              [7 + 3j, 8 + 6j, 9 + 9j]])
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.nbytes)
print(a.real, a.imag, sep='\n')
print(a.T)
print([elem for elem in a.flat])
b = a.tolist()
print(b)

(3, 3)
complex128
2
9
16
144
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1.+1.j 4.+2.j 7.+3.j]
 [2.+4.j 5.+5.j 8.+6.j]
 [3.+7.j 6.+8.j 9.+9.j]]
[(1+1j), (2+4j), (3+7j), (4+2j), (5+5j), (6+8j), (7+3j), (8+6j), (9+9j)]
[[(1+1j), (2+4j), (3+7j)], [(4+2j), (5+5j), (6+8j)], [(7+3j), (8+6j), (9+9j)]]
