In [3]:
import pandas as pd
import numpy as np

s = pd.Series(data=[1,2,3,4,5])
print(s)

# s = pd.Series(data=np.arange(0,10).reshape((2,5)))  # Series只能保存一维数组
# print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


Exception: Data must be 1-dimensional

In [4]:
import pandas as pd
import numpy as np

s = pd.Series(data=[1,2,3], index=["a", "b", "c"])
print(s)

a    1
b    2
c    3
dtype: int64


In [7]:
import pandas as pd
import numpy as np

s = pd.Series(data=[1,2,3,4,5], index=["a", "b", "c", "d", "e"])
print(s[1])  # 隐式索引取值
print(s.loc["a"])  #显示索引取值

print(s[0:3])
print(s['a':'d'])

2
1
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


In [8]:
import pandas as pd
import numpy as np

s = pd.Series(data=[1,2,3,4,5], index=["a", "b", "c", "d", "e"])

print(s.head(3))
print(s.tail(2))

a    1
b    2
c    3
dtype: int64
d    4
e    5
dtype: int64


In [9]:
import pandas as pd
import numpy as np

s = pd.Series(data=[1,1,2,2,3,4,5,8, 8, 9,10,2])
s.unique()  # 去重

array([ 1,  2,  3,  4,  5,  8,  9, 10], dtype=int64)

In [13]:
import pandas as pd
import numpy as np

s1 = pd.Series(data=[1,2,3,4,5], index=["a", "b", "c", "d", "e"])
s2 = pd.Series(data=[1,2,3,4,5], index=["a", "b", "f", "d", "e"])

s = s1+s2
# series支持掩码取值，取出索引位置对应为True值
s[s.notna()]

a     2.0
b     4.0
d     8.0
e    10.0
dtype: float64

In [14]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randint(0, 100, size=(3,4)), index=['a', 'b', 'c'], columns=['A','B','C','D'])
df

A   B   C   D
a  73  86  79  75
b  86  99  31  63
c   2  73  61  98

In [16]:
import pandas as pd

dic = {"A": [1,2,3,4],
       "B": [2,3,4,5],
       "C": [3,4,5,6],
       "D": [4,5,6,7]
       }

df = pd.DataFrame(data=dic, index=['a', 'b', 'c', 'd'])
print(df.values)
print(df.columns)
print(df.index)
print(df.shape)
print(df.size)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['a', 'b', 'c', 'd'], dtype='object')
(4, 4)
16


In [29]:
import pandas as pd

dic = {"A": [1,2,3,4],
       "B": [2,3,4,5],
       "C": [3,4,5,6],
       "D": [4,5,6,7]
       }

df = pd.DataFrame(data=dic, index=['a', 'b', 'c', 'd'])

# print(df['A'])  # 取一列
# print(df[['A', 'B']])  # 取两列
# print("====")
# print(df.loc["a"]) # 取一行，只能指定显示索引
# # print(df.loc[0]) # 不能指定显示索引
# print(df.iloc[0])  # 取一行，只能指定隐式索引
# print(df.iloc[[0, 1]])  # 取两行
#
# print(df['A']['a'])  # 取(a,A)对应的元素
# print(df.loc['a','A'])  # 取(a,A)对应的元素
# print(df.loc[['a','b'],'A'])  # 取(a,A),(b,A)对应的元素


df[0:2]  # 切取前两行
df.iloc[:,0:1]  # 切取第一列，与ndarray相同

A
a  1
b  2
c  3
d  4

- 使用tushare包获取某股票的历史行情数据。
- 输出该股票所有收盘比开盘上涨3%以上的日期。
- 输出该股票所有开盘比前日收盘跌幅超过2%的日期。
- 假如我从2010年1月1日开始，每月第一个交易日买入1手股票，每年最后一个交易日卖出所有股票，到今天为止，我的收益如何？


In [31]:
# 获取数据并保存
import tushare as ts
df = ts.get_k_data('600519',start='1900-01-01')
df.to_csv('./maotai.csv')

本接口即将停止更新，请尽快使用Pro版接口：https://waditu.com/document/2


In [32]:
# 读取数据,将并date列转为行索引
df = pd.read_csv('./maotai.csv', index_col='date', parse_dates=['date'])
df.drop(labels='Unnamed: 0',axis=1,inplace=True)

open  close   high    low     volume    code
date                                                     
2001-08-27  5.392  5.554  5.902  5.132  406318.00  600519
2001-08-28  5.467  5.759  5.781  5.407  129647.79  600519

In [36]:
# 输出该股票所有收盘比开盘上涨3%以上的日期。
is_true = (df['close'] - df['open'])/df['open'] > 0.03
df.loc[is_true].index  # 返回满足需求的数据

DatetimeIndex(['2001-08-27', '2001-08-28', '2001-09-10', '2001-12-21',
               '2002-01-18', '2002-01-31', '2003-01-14', '2003-10-29',
               '2004-01-05', '2004-01-14',
               ...
               '2021-01-05', '2021-01-12', '2021-01-25', '2021-02-04',
               '2021-02-09', '2021-02-10', '2021-03-03', '2021-03-05',
               '2021-03-11', '2021-04-02'],
              dtype='datetime64[ns]', name='date', length=326, freq=None)

In [41]:
# 输出该股票所有开盘比前日收盘跌幅超过2%的日期
(df['open']-df['close'].shift(1))/df['close'].shift(1) < -0.02
df.loc[(df['open']-df['close'].shift(1))/df['close'].shift(1) < -0.02].index
# shift(n)数据整体移动

DatetimeIndex(['2001-09-12', '2002-06-26', '2002-12-13', '2004-07-01',
               '2004-10-29', '2006-08-21', '2006-08-23', '2007-01-25',
               '2007-02-01', '2007-02-06', '2007-03-19', '2007-05-21',
               '2007-05-30', '2007-06-05', '2007-07-27', '2007-09-05',
               '2007-09-10', '2008-03-13', '2008-03-17', '2008-03-25',
               '2008-03-27', '2008-04-22', '2008-04-23', '2008-04-29',
               '2008-05-13', '2008-06-10', '2008-06-13', '2008-06-24',
               '2008-06-27', '2008-08-11', '2008-08-19', '2008-09-23',
               '2008-10-10', '2008-10-15', '2008-10-16', '2008-10-20',
               '2008-10-23', '2008-10-27', '2008-11-06', '2008-11-12',
               '2008-11-20', '2008-11-21', '2008-12-02', '2009-02-27',
               '2009-03-25', '2009-08-13', '2010-04-26', '2010-04-30',
               '2011-08-05', '2012-03-27', '2012-08-10', '2012-11-22',
               '2012-12-04', '2012-12-24', '2013-01-16', '2013-01-25',
      

- 假如我从2010年1月1日开始，每月第一个交易日买入1手股票，每年最后一个交易日卖出所有股票，到今天为止，我的收益如何？
- 分析：
    - 规则：基于开盘价股票的买卖
    - 买：一个完整的年需要买12次股票，一次买入100只，一个完整的年需要买入1200只（单价：当天开盘价）
    - 卖：一个完整的年需要卖一次股票，一次卖出1200只
    - 备注：19年不是一个完整的年，该年只可以买入900只，并且卖不出去

In [54]:
df_new = df['2010':'2021']  # 按年切片
#数据的重新取样的机制(resample):根据指定好的规则进行指定数据的提取
df_monthly = df_new.resample('M').first()
# 买股票
a = df_monthly['open'].sum()*100

# 卖股票
df_yearly = df_new.resample('A').last()
df_yearly = df_yearly[:-1]

b = df_yearly['open'].sum()*1200
# 剩余的计算到b中
b += df.iloc[-1]['close']*300
(b - a)/a  # 收益率

0.16103447089395448